### ISSUE TITLE
Address regressions in JSON serialization

### ISSUE THREAD

**Issue by aflinchb** [Azure-Samples/helium-csharp#25]
- Remove "deathYear" from API output when the field does not exist in the database's Actor document (when the actor is still alive), currently, it defaults to 0 when the field does not exist. 
- Check for any other regressions that may have been introduced after upgrade to dotnet 3.0

**Comment by bartr** [comment]
When we converted to dotnet 3.1, we converted to System.Text.Json instead of Newtonsoft.Json

System.Text.Json does not support the following yet:

- Ordering Properties
- Ignoring properties with default values (zero in the case of deathYear)

I recommend we revert back to Newtonsoft.Json for serialization until these features are available as they impact the developer experience.

@aflinchb  @jofultz

**Comment by aflinchb** [comment]
Reverting to Newtonsoft.Json sounds good to me.
